### ISSUE TITLE
Problem with running on Ubuntu

### ISSUE THREAD

**Issue by sratatata** [sratatata/space-invaders#13]
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL is not supported by the video driver.
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:322)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:216)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:144)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: org.lwjgl.LWJGLException: X Error - disp: 0x7f1e3001d220 serial: 176 error: BadValue (integer parameter out of range for operation) request_code: 154 minor_code: 24
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
	at org.lwjgl.opengl.LinuxContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.LinuxContextImplementation.create(LinuxContextImplementation.java:51)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:132)
	at org.lwjgl.opengl.Display.create(Display.java:850)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:314)
	... 3 more
```

**Comment by sratatata** [comment]
Fixed. 

Problem with nvidia drivers. 
I've installed nvidia drivers (forgot I've Intel 4400). After removing fault driver, everything is back to normal.
